#!/bin/bash

Beep() {

    BEEP_VOL="60%"

    CURRENT_VOL="$(amixer sget Master | grep -m1 "\[on\]" | awk '{print $5}' | tr -d '[]')"
    amixer sset Master $BEEP_VOL >/dev/null 2>&1

    (
        speaker-test -t sine -f 600 >/dev/null 2>&1 &
        BEEP_PID=$!
        sleep 0.2
        kill -9 $BEEP_PID 2>/dev/null
    )

    amixer sset Master $CURRENT_VOL >/dev/null 2>&1
}

# Create and remove temp file
SCR_IMG=$(mktemp)
trap "rm $SCR_IMG*" EXIT

scrot --select $SCR_IMG.jpg -q 100

# Scale screenshot to 400%
mogrify -modulate 100,0 -resize 400% $SCR_IMG.jpg

# Validar si tiene internet
wget -q --spider http://google.com

# Capture text to imagen temp
if [ $? -eq 0 ]; then
    echo "Online"

    $HOME/.asdf/shims/gcloud ml vision detect-text --language-hints=es $SCR_IMG.jpg >$SCR_IMG.json
    echo -e "$(cat $SCR_IMG.json | jq '.responses[].fullTextAnnotation.text')" | tr '\n' ' ' | tr '  ' ' ' | xargs | xclip -selection c
else
    echo "Offline"
    # Set lang to OCR
    tesseract_lang="spa"

    # Capture text to imagen temp
    tesseract $SCR_IMG.jpg $SCR_IMG &>/dev/null
    cat $SCR_IMG.txt

    # Copy text to clipboard
    cat $SCR_IMG.txt | tr '\n' ' ' | xargs | xclip -selection c

fi

Beep
exit
