version: '3'
services:
  gatsby:
    container_name: gatsby
    build:
      context: .
      dockerfile:  Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - '$PWD/app:/usr/app/:delegated'
    stdin_open: true
    tty: true
